import { describe, expect, it } from "vitest";
import { detectBlockedSignalsFromStrings } from "./capturePageSetup.js";

describe("detectBlockedSignalsFromStrings", () => {
	it("detects 403 error title (common CloudFront)", () => {
		const title = "403 ERROR";
		const text = "Request blocked.";
		const html = "<html></html>";
		expect(detectBlockedSignalsFromStrings(title, text, html)).toBe("title_403");
	});

	it("detects CloudFront body when title is generic (HTTP 200 HTML error)", () => {
		const title = "Error";
		const text =
			"The request could not be satisfied. Request blocked. We can't connect to the server.";
		const html =
			"<html><body>ERROR</body></html> Generated by cloudfront (CloudFront)";
		expect(detectBlockedSignalsFromStrings(title, text, html)).toBe(
			"cf_satisfied"
		);
	});

	it("detects generated by cloudfront footer", () => {
		const html = "<p>oops</p> generated by cloudfront";
		expect(
			detectBlockedSignalsFromStrings("Error", "something", html)
		).toBe("cf_generated");
	});

	it("returns null for normal marketing copy", () => {
		expect(
			detectBlockedSignalsFromStrings(
				"Welcome",
				"Our kindergarten welcomes you.",
				"<div>hello</div>"
			)
		).toBeNull();
	});
});
