import { isFigmaUrl } from "./figmaUrl.js";

/** Recent Chrome UA — helps avoid naive bot blocks (not a guarantee for Figma). */
const CHROME_USER_AGENT =
	"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

/**
 * Reduce automation signals and mimic a normal desktop Chrome navigation.
 * Call once per page, before the first goto().
 * @param {import("puppeteer").Page} page
 */
export async function setupCapturePage(page) {
	await page.setUserAgent(CHROME_USER_AGENT);
	await page.setExtraHTTPHeaders({
		"Accept-Language": "en-US,en;q=0.9",
		Accept:
			"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
		"Sec-Fetch-Dest": "document",
		"Sec-Fetch-Mode": "navigate",
		"Sec-Fetch-Site": "none",
		"Upgrade-Insecure-Requests": "1",
	});
	await page.evaluateOnNewDocument(() => {
		Object.defineProperty(navigator, "webdriver", {
			get: () => undefined,
		});
	});
}

/**
 * Pure matcher for tests (and same logic as evaluate in-page).
 * @param {string} title
 * @param {string} text
 * @param {string} html
 * @returns {string | null}
 */
export function detectBlockedSignalsFromStrings(title, text, html) {
	const t = (title || "").toLowerCase();
	const textLc = (text || "").toLowerCase();
	const htmlLc = (html || "").toLowerCase();

	if (t.includes("403") && t.includes("error")) return "title_403";
	if (textLc.includes("the request could not be satisfied")) return "cf_satisfied";
	if (textLc.includes("could not be satisfied")) return "cf_satisfied_short";
	if (textLc.includes("request blocked")) return "request_blocked";
	if (textLc.includes("403 error") || textLc.includes("403 forbidden")) {
		return "text_403";
	}
	if (htmlLc.includes("generated by cloudfront")) return "cf_generated";
	if (
		htmlLc.includes("cloudfront") &&
		(textLc.includes("error") || textLc.includes("blocked"))
	) {
		return "cf_html";
	}
	if (
		textLc.includes("amazon cloudfront") ||
		htmlLc.includes("amazon cloudfront")
	) {
		return "cf_brand";
	}
	return null;
}

/**
 * Detects CloudFront / CDN block pages. Many return HTTP 200 with an HTML error body
 * (so response.status() alone is not enough).
 *
 * Important: logic must live *inside* page.evaluate — Puppeteer runs this in the
 * browser context, so it cannot call outer functions (e.g. detectBlockedSignalsFromStrings).
 * Keep checks aligned with {@link detectBlockedSignalsFromStrings}.
 */
async function throwIfBlockedOrErrorPage(page, loadedUrl) {
	const issue = await page.evaluate(() => {
		const title = document.title || "";
		const text = (
			document.body?.innerText ||
			document.body?.textContent ||
			""
		).slice(0, 12000);
		const html = (document.documentElement?.innerHTML || "").slice(0, 24000);
		const t = (title || "").toLowerCase();
		const textLc = (text || "").toLowerCase();
		const htmlLc = (html || "").toLowerCase();
		if (t.includes("403") && t.includes("error")) return "title_403";
		if (textLc.includes("the request could not be satisfied")) return "cf_satisfied";
		if (textLc.includes("could not be satisfied")) return "cf_satisfied_short";
		if (textLc.includes("request blocked")) return "request_blocked";
		if (textLc.includes("403 error") || textLc.includes("403 forbidden")) {
			return "text_403";
		}
		if (htmlLc.includes("generated by cloudfront")) return "cf_generated";
		if (
			htmlLc.includes("cloudfront") &&
			(textLc.includes("error") || textLc.includes("blocked"))
		) {
			return "cf_html";
		}
		if (
			textLc.includes("amazon cloudfront") ||
			htmlLc.includes("amazon cloudfront")
		) {
			return "cf_brand";
		}
		return null;
	});
	if (!issue) return;
	const figma = isFigmaUrl(loadedUrl);
	const prefix = figma
		? "CAPTURE_FIGMA_BLOCKED: Figma did not load the design (CDN or bot block page detected). "
		: "CAPTURE_PAGE_BLOCKED: The page returned an error or block screen instead of content. ";
	throw new Error(prefix + figmaAdvice(figma) + ` (signal: ${issue})`);
}

/**
 * Figma uses CloudFront; many datacenter / headless requests get HTTP 403 or an error HTML body.
 * @param {import("puppeteer").Page} page
 * @param {import("puppeteer").HTTPResponse | null | undefined} response
 * @param {string} loadedUrl — URL that was navigated to
 */
export async function assertCapturePageOk(page, response, loadedUrl) {
	const status = response?.status() ?? 0;
	if (status >= 400) {
		throw new Error(
			`CAPTURE_HTTP_${status}: Capture failed: HTTP ${status} for ${loadedUrl}. ` +
				figmaAdvice(isFigmaUrl(loadedUrl))
		);
	}

	await throwIfBlockedOrErrorPage(page, loadedUrl);
}

/**
 * Run after extra wait — error text can paint after first frame.
 * @param {import("puppeteer").Page} page
 * @param {string} loadedUrl
 */
export async function assertCapturePageOkContentOnly(page, loadedUrl) {
	await throwIfBlockedOrErrorPage(page, loadedUrl);
}

function figmaAdvice(figma) {
	if (!figma) {
		return "Check that the URL is public and opens in a normal browser.";
	}
	return (
		"Figma often blocks automated browsers and cloud/datacenter IPs (AWS, Cloudflare, etc.), even when the file is public in your browser. " +
		"What works reliably: export a PNG from Figma (right‑click frame → Export, or Share → export) and use **Design (PNG) vs URL** in this app; " +
		"or share a **Figma prototype** link with “Anyone with the link” and try **Figma embed URL for capture** in Settings. " +
		"If you self‑host this server, testing from a residential network sometimes succeeds where cloud IPs are blocked."
	);
}

/**
 * Figma’s editor never reaches networkidle; use domcontentloaded + a short paint delay unless the caller chose something else.
 * @param {string} url
 * @param {string} waitUntil
 * @param {number} postDelayMs
 * @returns {{ effectiveWait: string; effectivePostDelayMs: number }}
 */
export function resolveFigmaTiming(url, waitUntil, postDelayMs) {
	if (!isFigmaUrl(url)) {
		return { effectiveWait: waitUntil, effectivePostDelayMs: postDelayMs };
	}
	let effectiveWait = waitUntil;
	if (waitUntil === "networkidle2" || waitUntil === "networkidle0") {
		effectiveWait = "domcontentloaded";
	}
	const effectivePostDelayMs = Math.max(postDelayMs, 2800);
	return { effectiveWait, effectivePostDelayMs };
}

/**
 * When either URL is Figma, relax wait strategy for both tabs (parallel navigations).
 */
export function resolveDualFigmaTiming(urlA, urlB, waitUntil, postDelayMs) {
	const figma = isFigmaUrl(urlA) || isFigmaUrl(urlB);
	if (!figma) {
		return { effectiveWait: waitUntil, effectivePostDelayMs: postDelayMs };
	}
	let effectiveWait = waitUntil;
	if (waitUntil === "networkidle2" || waitUntil === "networkidle0") {
		effectiveWait = "domcontentloaded";
	}
	return {
		effectiveWait,
		effectivePostDelayMs: Math.max(postDelayMs, 2800),
	};
}
